spring:
  cloud:
    gateway:
      routes:
        - id: qq_test
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: baidu_test
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
### 前端项目 带api前缀

